ナビバー追加
T-Tsujii/gyakuten_clone_group34 pull request #12
Opened 2020-11-03 08:33 UTC by chimaquen

## 実装内容

- Bootstrapを使用してナビバーを作成
- 教材の各項目設定（リンクは”＃”のまま）
- ログイン前後でリンクが変わる様に設定

## 参考資料

- 逆転教材　”Bootstrap　投稿アプリ・その３、導入”
- Bootstrap公式
- MDN

## チェックリスト

※ プルリクを出した後にクリックでチェックできます

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2020-11-03 08:52 UTC, T-Tsujii requested changes

2020-11-03 08:52 UTC, T-Tsujii commented on app/views/layouts/_header.html.erb
> +  </div>
```suggestion
    </nav>
  </div>
```

2020-11-03 08:52 UTC, T-Tsujii commented on app/views/layouts/_header.html.erb
> +<header class="navbar-fixed-top base-color bg-primary">
スタイルのついていないクラスがいくつかあるようです。`fixed-top` というクラスはBootstrapに用意されていますが， `navbar-fixed-top` というクラスはありません。

3行目も不要なクラスは削除しましょう。

```suggestion
<header class="fixed-top base-color bg-primary">
```

2020-11-03 08:59 UTC, T-Tsujii requested changes

2020-11-03 08:59 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +  }
こちらはBootstrapで入っているスタイルと同じではありませんか？

2020-11-03 08:59 UTC, T-Tsujii commented
横幅が短い場合のハンバーガーメニューが表示されていないようです。

2020-11-03 22:17 UTC, chimaquen commented on app/views/layouts/_header.html.erb
> +<header class="navbar-fixed-top base-color bg-primary">
表示をさせるときに、確認したところ、`navbar-fixed-top`　にしないと、
表示されません。

調べたところ、このクラス名はBootstrap4以前のものと書いてあったのですが
自分のバージョンが古いのでしょうか？

2020-11-03 23:01 UTC, chimaquen commented on app/assets/stylesheets/application.scss
> +  }
こちらは削除いたします。

2020-11-04 07:07 UTC, T-Tsujii requested changes

2020-11-04 07:07 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +
ページの一部ヘッダーに隠れてしまっています。
他にもいろいろスタイルが入っていますが，一度ここからスタートして必要なものを入れていきましょう。

```suggestion
body {
  padding-top: 56px;
}
header {
  .header-nav {
    max-width: 1100px;
    margin-left: auto;
    margin-right: auto;
  }
}

header {
  .header-nav {
    max-width: 1100px;
    margin-left: auto;
    margin-right: auto;
  }
}
```

2020-11-04 07:07 UTC, T-Tsujii commented on app/views/layouts/_header.html.erb
> +</header>
この状態で動作しますので，必要があれば原因を調べていただけますか。

```suggestion
<header class="fixed-top bg-primary">
  <nav class="navbar navbar-expand-lg navbar-dark header-nav">
    <%= link_to "やんばるCODE", '#', class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active dropdown">
          <%= link_to "Rails", "#", class: "nav-link dropdown-toggle", id: "navbar-dropdown-rails", role: "button", data: { toggle: "dropdown"}, aria: { haspopup: true, expanded:false } %>
          <div class="dropdown-menu" aria-labelledby="navbar-dropdown-rails">
            <%= link_to "Ruby/Rails教材", "#", class: "dropdown-item" %>
            <%= link_to "動画教材", "#", class: "dropdown-item" %>
            <%= link_to "AWS講座", "#", class: "dropdown-item" %>
            <%= link_to "プログラミング勉強会", "#", class: "dropdown-item" %>
            <%= link_to "質問集", "#", class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item"><%= link_to "対談", "#", class: "nav-link active" %></li>
        <li class="nav-item"><%= link_to "動画編集講座", "#", class: "nav-link active" %></li>
        <li class="nav-item"><%= link_to "ライティング講座", "#", class: "nav-link active" %></li>
        <li class="nav-item"><%= link_to "マネタイズ講座", "#", class: "nav-link active" %></li>
        <li class="nav-item active dropdown">
          <%= link_to "PHP", "#", class: "nav-link dropdown-toggle", id: "navbar-dropdown-php", role: "button", data: { toggle: "dropdown"}, aria: { haspopup: true, expanded:false } %>
          <div class="dropdown-menu" aria-labelledby="navbar-dropdown-php">
            <%= link_to "PHPテキスト教材", "#", class: "dropdown-item" %>
            <%= link_to "PHP動画教材", "#", class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item"><%= link_to "LINE@", "#", class: "nav-item nav-link active" %></li>
        <% if user_signed_in? %>
          <li class="nav-item active dropdown">
            <%= link_to "マイページ", "#", class: "nav-link dropdown-toggle", id: "navbar-dropdown-mypage", role: "button", data: { toggle: "dropdown"}, aria: { haspopup: true, expanded:false } %>
            <div class="dropdown-menu" aria-labelledby="navbar-dropdown-mypage">
              <%= link_to "進捗管理", "#", class: "dropdown-item" %>
              <%= link_to "アカウント編集", edit_user_registration_path, class: "dropdown-item" %>
            </div>
          </li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link active" %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path, class: "nav-link active" %></li>
          <li><%= link_to "ログイン", new_user_session_path, class: "nav-link active" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
```

2020-11-06 23:42 UTC, T-Tsujii requested changes

2020-11-06 23:42 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> -    <header>
- `<header>`タグが消えてしまっています。

2020-11-08 05:09 UTC, T-Tsujii approved these changes

2020-11-08 05:10 UTC, merged