16_AWSテキスト教材一覧ページの実装
T-Tsujii/gyakuten_clone_group34 pull request #13
Opened 2020-11-03 20:44 UTC by ju-to-sh

## 実装内容

- AWS教材の一覧ページを作成(tableタグを使用)
- 広告部分の作成

## 参考資料

- Bootstrap基礎（その2）
  - [やんばるCODEアプリ](https://arcane-gorge-21903.herokuapp.com/texts/261)

## チェックリスト

※ プルリクを出した後にクリックでチェックできます

- [ ] 影響し得る範囲のローカル環境での動作確認

2020-11-04 00:43 UTC, T-Tsujii requested changes

2020-11-04 00:43 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +    <p>サロン特別割引適用パスワード：gyakutenseyo</p>
`Take_off_Rails` の広告は外して下さい。画像も削除していただきたいと思います。

2020-11-04 00:43 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +            </li>
ログイン時とログアウト時で表示を切り替えるようにしましょう。

2020-11-04 00:43 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +            </li>
マイページの箇所もドロップダウン になっています。

2020-11-04 00:43 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +        </tr>
具体的に書くのではなく，aws_textsテーブルのデータを一覧表示する形式にしましょう。

2020-11-04 00:43 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +}
直接imgタグにスタイルを入れては影響範囲が大きすぎます。
クラスを付けて対処しましょう。

2020-11-06 21:52 UTC, ju-to-sh commented
# 修正
- Take off Railsの広告を削除
- ログイン時とログアウト時で表示切替
- マイページの箇所をドロップダウンに変更
- aws_textsテーブルのデータを一覧表示する形式に変更
- bannerクラスのimgについてクラスをつけて対応

2020-11-07 02:03 UTC, T-Tsujii commented
画像がGitから削除されていません。次のコマンドを実行しましょう。

```
git rm -f app/assets/images/take_off_rails.jpg
```

2020-11-07 02:13 UTC, T-Tsujii requested changes

2020-11-07 02:13 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +    <header class="main-color fixed-top">
前回気付きませんでしたが，このタスクはAWSテキスト教材の実装タスクであって，ヘッダーやフッターのタスクではありません。

ヘッダーのタスクは別の方が行っておりますので，このファイルの差分は消去して下さい。

チーム開発でタスクと関係のない変更を加えるのは原則アウトです。

もし，AWS教材へのリンクが付けられないという理由で実装されたのであれば，まずヘッダーを実装されている方と相談するなどの対応を行うべきです。

```
git checkout ae15e2c3ff1715177f3f954973bd09f84d818573 app/views/layouts/application.html.erb
```

2020-11-07 02:13 UTC, T-Tsujii commented on app/views/aws_texts/index.html.erb
> +            <th><%= aws_text.id %></th>
`id`は1からスタートする保証はありません。`each.with_index(1)`を使うべきです。

2020-11-07 02:57 UTC, ju-to-sh commented on app/views/layouts/application.html.erb
> +    <header class="main-color fixed-top">
すみません。タスク内容を勘違いしておりました。ナビバーの実装が完了されるのを待ちたいと思います。

2020-11-08 21:56 UTC, ju-to-sh commented
# 修正
- Take off Railsの画像を gitから削除
- フッダー、ヘッダーの差分を削除
- フッダー、ヘッダーの不要なスタイリングの削除
- each.with_indexメソッドを使用するように修正

2020-11-09 06:43 UTC, T-Tsujii requested changes

2020-11-09 06:43 UTC, T-Tsujii commented on app/views/aws_texts/index.html.erb
> +            <th><%= aws_text.id %></th>
`id` を使用したままになっていますよ！

```suggestion
        <% @aws_texts.each.with_index(1) do |aws_text, index| %>
          <tr>
            <th><%= index %></th>
```

2020-11-09 06:43 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +    </nav>
こちらは元に戻しましょう。

```suggestion
    </main>
    <footer>
    </footer>
```

2020-11-09 21:31 UTC, ju-to-sh commented
# 修正
- each.with_indexメソッドを使用するように修正
- app/views/layouts/application.html.erb にfooterタグを復元

2020-11-10 09:40 UTC, T-Tsujii approved these changes

2020-11-10 09:40 UTC, merged