deviseでログイン機能実装
T-Tsujii/gyakuten_clone_group34 pull request #9
Opened 2020-10-25 10:05 UTC by chimaquen

## 実装内容
- `devise`  を利用して，ユーザーのログイン機能を実装
- 新規登録・ログイン・ログアウトのリンクを，全てのページの一番上に追加
- `db/seeds.rb`にテスト用ユーザーを作成
- 全てのページをログイン必須に変更

## 参考資料
- 逆転教材　Railsログイン機能、deviseを使ったログイン機能の実装

## チェックリスト

※ プルリクを出した後にクリックでチェックできます

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2020-10-25 13:51 UTC, T-Tsujii requested changes

2020-10-25 13:51 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +      <%= link_to "新規登録", new_user_registration_path %>
ログイン時にログインや新規登録が表示されていてはいけません。ログアウトも同様です。

2020-10-25 13:51 UTC, T-Tsujii commented
コンフリクトの解消もお願いします。

2020-10-26 11:47 UTC, chimaquen commented
# 修正

- ビューページの上部修正
- ルーティングの修正

2020-10-26 13:15 UTC, T-Tsujii requested changes

2020-10-26 13:15 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +        <%= link_to "ログアウト", destroy_user_session_path %>
`method` の指定が抜けています。これではログアウトできないですよ。

```suggestion
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
```

2020-10-26 13:44 UTC, chimaquen commented on app/views/layouts/application.html.erb
> +        <%= link_to "ログアウト", destroy_user_session_path %>
そうでした。GET以外は入れなければいけませんでした。すいません！！

2020-10-26 14:09 UTC, chimaquen commented
# 修正

- application.html.erbファイルのログアウト部分、メソッド追記

2020-11-01 12:29 UTC, T-Tsujii requested changes

2020-11-01 12:29 UTC, T-Tsujii commented on Gemfile
> +gem 'webpacker', '~> 4.0'
2つ存在しています。
```suggestion
```

2020-11-01 22:11 UTC, T-Tsujii approved these changes

2020-11-01 22:11 UTC, merged